# Specify Base Image
FROM python:3.8.10-slim

# Set working dir
WORKDIR /app

# Install Dependencies
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Default Commands
CMD ["flask", "run", "--host", "0.0.0.0"]